/**
 * Audio entity types
 */

import type { SyncableEntity, AudioProvider } from './common'

// ============================================================================
// Core Entity
// ============================================================================

/**
 * Audio content
 *
 * In this project, all audios are user-uploaded (provider is always 'user').
 * Audios can be added from local files, downloaded from URLs, or generated by TTS.
 *
 * ID generation: UUID v5 with `audio:user:${aid}`
 * - aid is SHA-256 hash of the audio file
 * - For TTS audio: aid is SHA-256 hash of the generated audio blob
 */
export interface Audio extends SyncableEntity {
  id: string // UUID v5 (generated from provider='user' + aid)
  aid: string // SHA-256 hash of the audio file (used as aid with provider 'user')
  provider: AudioProvider // Always 'user' in this project (kept for backend compatibility)
  title: string
  description?: string
  thumbnailUrl?: string
  duration: number // seconds
  language: string // BCP 47
  createdAt: string // ISO 8601
  updatedAt: string // ISO 8601

  // TTS-specific fields (for AI-generated audio)
  translationKey?: string // Reference to Translation.id
  sourceText?: string // Original text synthesized
  voice?: string // Voice identifier used

  // Original source (if added from URL)
  source?: string // ✅ 可同步 - Original URL if downloaded from web

  // Local file storage
  // - For user-uploaded files (usually large): use fileHandle pointing to user's file system
  // - For TTS-generated audio (usually small < 1MB): use blob stored directly in IndexedDB
  fileHandle?: FileSystemFileHandle // ❌ 本地 - For user-uploaded files, stored in IndexedDB, not serializable
  blob?: Blob // ❌ 本地 - For TTS-generated small files, stored directly in IndexedDB

  // File verification (synced for cross-device verification)
  md5?: string // ✅ 可同步 - File hash (SHA-256, same as aid)
  size?: number // ✅ 可同步 - File size in bytes

  // Server storage (optional, for small files or user preference)
  mediaUrl?: string // ✅ 可同步 - Server URL if file is uploaded (optional)
}

// ============================================================================
// Store Input Types
// ============================================================================

/**
 * Input type for creating TTS audio
 * Note: TTS audio stores blob directly in IndexedDB (usually small, < 1MB)
 */
export type TTSAudioInput = Omit<Audio, 'id' | 'aid' | 'createdAt' | 'updatedAt' | 'blob' | 'fileHandle'> & {
  provider: 'user'
  sourceText: string
  voice: string
  blob: Blob // Required for TTS - will be stored directly in IndexedDB
}

/**
 * Input type for creating user-uploaded audio (local file or URL download)
 */
export type UserAudioInput = Omit<Audio, 'id' | 'createdAt' | 'updatedAt'> & {
  provider?: 'user' // Optional, defaults to 'user'
  aid?: string // Optional, will be calculated from fileHandle if not provided
  source?: string // Optional URL if downloaded from web
}
