/**
 * Local Model Result Types
 */

export interface LocalASRResult {
  text: string
  segments?: Array<{
    text: string
    start: number
    end: number
  }>
  language?: string
}

export interface LocalTranslationResult {
  translatedText: string
  sourceLanguage?: string
  targetLanguage?: string
}

export interface LocalDictionaryResult {
  word: string
  definitions: Array<{
    partOfSpeech: string
    definition: string
    translation: string
  }>
  contextualExplanation?: string
}

/**
 * TTS Transcript Item with timing information (local version)
 * Matches TranscriptLine format from db schema for consistency
 * Timeline uses milliseconds (integer) for precision
 *
 * Structure: Sentence -> Word (nested via timeline)
 */
export interface LocalTTSTranscriptItem {
  text: string
  start: number // milliseconds
  duration: number // milliseconds
  timeline?: LocalTTSTranscriptItem[] // nested: Sentence → Word
  confidence?: number // 0-1
}

/**
 * TTS Transcript with sentence-level timestamps and nested word timeline
 * Follows db schema TranscriptLine format
 */
export interface LocalTTSTranscript {
  /**
   * Sentence-level items with optional word-level timeline
   * Each item has: text, start (ms), duration (ms), timeline (words)
   */
  timeline: LocalTTSTranscriptItem[]
}

export interface LocalTTSResult {
  audioBlob: Blob
  format: string
  duration?: number
  /**
   * Transcript with timestamps in TranscriptLine format
   * Generated by Kokoro TTS timestamped model
   * Structure: Sentence → Word (nested via timeline)
   */
  transcript?: LocalTTSTranscript
}

