/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerMonitorRouteImport } from './routes/worker-monitor'
import { Route as VoiceSynthesisRouteImport } from './routes/voice-synthesis'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SmartTranslationRouteImport } from './routes/smart-translation'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as IndexRouteImport } from './routes/index'

const WorkerMonitorRoute = WorkerMonitorRouteImport.update({
  id: '/worker-monitor',
  path: '/worker-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceSynthesisRoute = VoiceSynthesisRouteImport.update({
  id: '/voice-synthesis',
  path: '/voice-synthesis',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartTranslationRoute = SmartTranslationRouteImport.update({
  id: '/smart-translation',
  path: '/smart-translation',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/smart-translation': typeof SmartTranslationRoute
  '/sync': typeof SyncRoute
  '/vocabulary': typeof VocabularyRoute
  '/voice-synthesis': typeof VoiceSynthesisRoute
  '/worker-monitor': typeof WorkerMonitorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/smart-translation': typeof SmartTranslationRoute
  '/sync': typeof SyncRoute
  '/vocabulary': typeof VocabularyRoute
  '/voice-synthesis': typeof VoiceSynthesisRoute
  '/worker-monitor': typeof WorkerMonitorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/credits': typeof CreditsRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/smart-translation': typeof SmartTranslationRoute
  '/sync': typeof SyncRoute
  '/vocabulary': typeof VocabularyRoute
  '/voice-synthesis': typeof VoiceSynthesisRoute
  '/worker-monitor': typeof WorkerMonitorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credits'
    | '/library'
    | '/login'
    | '/settings'
    | '/smart-translation'
    | '/sync'
    | '/vocabulary'
    | '/voice-synthesis'
    | '/worker-monitor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/credits'
    | '/library'
    | '/login'
    | '/settings'
    | '/smart-translation'
    | '/sync'
    | '/vocabulary'
    | '/voice-synthesis'
    | '/worker-monitor'
  id:
    | '__root__'
    | '/'
    | '/credits'
    | '/library'
    | '/login'
    | '/settings'
    | '/smart-translation'
    | '/sync'
    | '/vocabulary'
    | '/voice-synthesis'
    | '/worker-monitor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreditsRoute: typeof CreditsRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SmartTranslationRoute: typeof SmartTranslationRoute
  SyncRoute: typeof SyncRoute
  VocabularyRoute: typeof VocabularyRoute
  VoiceSynthesisRoute: typeof VoiceSynthesisRoute
  WorkerMonitorRoute: typeof WorkerMonitorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker-monitor': {
      id: '/worker-monitor'
      path: '/worker-monitor'
      fullPath: '/worker-monitor'
      preLoaderRoute: typeof WorkerMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice-synthesis': {
      id: '/voice-synthesis'
      path: '/voice-synthesis'
      fullPath: '/voice-synthesis'
      preLoaderRoute: typeof VoiceSynthesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-translation': {
      id: '/smart-translation'
      path: '/smart-translation'
      fullPath: '/smart-translation'
      preLoaderRoute: typeof SmartTranslationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreditsRoute: CreditsRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SmartTranslationRoute: SmartTranslationRoute,
  SyncRoute: SyncRoute,
  VocabularyRoute: VocabularyRoute,
  VoiceSynthesisRoute: VoiceSynthesisRoute,
  WorkerMonitorRoute: WorkerMonitorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
