/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EchoIdRouteImport } from './routes/echo.$id'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EchoIdRoute = EchoIdRouteImport.update({
  id: '/echo/$id',
  path: '/echo/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/vocabulary': typeof VocabularyRoute
  '/echo/$id': typeof EchoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/vocabulary': typeof VocabularyRoute
  '/echo/$id': typeof EchoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/vocabulary': typeof VocabularyRoute
  '/echo/$id': typeof EchoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/library' | '/vocabulary' | '/echo/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library' | '/vocabulary' | '/echo/$id'
  id: '__root__' | '/' | '/library' | '/vocabulary' | '/echo/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  VocabularyRoute: typeof VocabularyRoute
  EchoIdRoute: typeof EchoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/echo/$id': {
      id: '/echo/$id'
      path: '/echo/$id'
      fullPath: '/echo/$id'
      preLoaderRoute: typeof EchoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  VocabularyRoute: VocabularyRoute,
  EchoIdRoute: EchoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
